server:
  address: localhost
  port: 8080
  servlet:
    encoding:
      force: true #mustache한글깨짐 해결

spring:
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/jpashop
    #    username: sa
    #    password:
    #    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: test
    password:

  jpa:
    database: mysql
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind.: trace
    #쿼리를 찍어줌

handlebars:
  suffix: .html
  expose-session-attributes: true #Spring handler에서 별도로 session값을 model에 설정하지 않아도 handlebars에서 가져올 수 있음

